import type { ForecastScenario, ScenarioPoint } from '../lib/types'
import { NATIONAL_PRICE } from '../data/prices'
import { LAST_MEASURED_QUARTER, addQuarters } from '../lib/quarters'
import { pctChange, std } from '../lib/stats'
import { VALUATION } from './valuation'

/**
 * Forecast engine (full derivation in docs/FORECAST_METHODOLOGY.md §5).
 *
 * NOT a price extrapolation. Quarterly growth is generated by a documented
 * factor model:
 *
 *   g(t) = w_m·momentum(t) + w_f·fundamental(t) + w_v·valuationPull(t)
 *
 *   momentum(t)      – observed recent growth, decaying with half-life 3 q
 *                      (markets are persistent but momentum fades)
 *   fundamental(t)   – scenario-dependent structural growth from: expected wage
 *                      growth, mortgage-rate path, supply gap, migration/demography,
 *                      construction costs, policy stance (per-scenario table below)
 *   valuationPull(t) – mean-reversion: −λ · composite misvaluation, distributed
 *                      over 12 quarters (overvalued markets grow below fundamentals)
 *
 * Confidence intervals: σ of historical 4-quarter changes (≈ observed forecast
 * error of a naive model) scaled by √horizon and a scenario uncertainty factor.
 * Scenario probabilities are analyst priors (documented) — not model outputs.
 */

export interface ScenarioAssumption {
  id: 'optimistic' | 'base' | 'pessimistic'
  label: string
  probability: number
  /** structural quarterly growth from fundamentals, % q/q at horizon start */
  fundamentalQ: number
  /** how fast fundamentals converge to long-run trend (0.8 %/q ≈ 3.2 % p.a. nominal, pod rastom miezd) */
  fundamentalDecay: number
  /** valuation mean-reversion intensity per quarter (share of gap closed) */
  reversion: number
  /** how much of the observed market momentum survives the scenario's shock */
  momentumFactor: number
  uncertainty: number
  assumptions: string[]
}

export const SCENARIOS: ScenarioAssumption[] = [
  {
    id: 'optimistic',
    label: 'Optimistický',
    probability: 0.25,
    fundamentalQ: 1.9,
    fundamentalDecay: 0.96,
    reversion: 0.004,
    momentumFactor: 1.05,
    uncertainty: 1.15,
    assumptions: [
      'ECB zníži sadzby k 1,5 %; hypotéky ~3,0 % do konca 2027',
      'Rast miezd 6–7 % ročne, nezamestnanosť < 5 %',
      'Výstavba zostáva utlmená (< 17-tis. dokončených bytov/rok) — ponukový deficit trvá',
      'Silná investičná aktivita (Volvo nábeh, obranné výdavky, EÚ fondy)',
      'Bez externého šoku',
    ],
  },
  {
    id: 'base',
    label: 'Základný',
    probability: 0.5,
    fundamentalQ: 1.5,
    fundamentalDecay: 0.93,
    reversion: 0.009,
    momentumFactor: 0.85,
    uncertainty: 1.0,
    assumptions: [
      'ECB drží depozitnú sadzbu ~2,0 %; hypotéky 3,3–3,6 %',
      'Rast miezd ~5 % ročne, inflácia 2,5–3,5 %',
      'HDP +1–2 % (fiškálna konsolidácia brzdí)',
      'Postupné ochladenie z +12 % (2025) k jednociferným tempám',
      'Mierny nárast dokončených bytov od 2027',
    ],
  },
  {
    id: 'pessimistic',
    label: 'Pesimistický',
    probability: 0.25,
    fundamentalQ: -0.8,
    fundamentalDecay: 0.9,
    reversion: 0.02,
    momentumFactor: 0.35,
    uncertainty: 1.25,
    assumptions: [
      'Recesia v eurozóne / obchodné šoky; nezamestnanosť > 6,5 %',
      'Inflácia núti ECB držať alebo zvýšiť sadzby; hypotéky > 4,5 %',
      'Tvrdšia fiškálna konsolidácia zráža disponibilné príjmy',
      'Nadhodnotenie sa koriguje nominálnym poklesom cien',
      'Geopolitická eskalácia (vojna, energie)',
    ],
  },
]

export const FORECAST_HORIZON_Q = 20 // 5 years

export function buildForecasts(): ForecastScenario[] {
  const v = NATIONAL_PRICE.values
  const last = v[v.length - 1]!
  const yoyHist = pctChange(v, 4).filter((x): x is number => x != null)
  const sigmaYoY = std(yoyHist) // ≈ historical dispersion of 4Q changes, pp

  // starting momentum: mean of last 2 quarterly growth rates
  const qoq = pctChange(v, 1)
  const m0 = ((qoq[qoq.length - 1] ?? 0) + (qoq[qoq.length - 2] ?? 0)) / 2

  const W_MOMENTUM = 0.45
  const W_FUND = 0.4
  const W_VAL = 0.15
  const MOMENTUM_DECAY = 0.7943 // half-life 3 quarters

  return SCENARIOS.map((sc) => {
    const points: ScenarioPoint[] = []
    let price = last
    let momentum = m0 * sc.momentumFactor
    let fundamental = sc.fundamentalQ
    let valuationGap = VALUATION.composite // % overvaluation, decays as prices adjust

    for (let h = 1; h <= FORECAST_HORIZON_Q; h++) {
      momentum *= MOMENTUM_DECAY
      fundamental = 0.8 + (fundamental - 0.8) * sc.fundamentalDecay
      // valuation drag: reversion×10 ≈ share of the misvaluation gap (in %) converted
      // to a q/q growth penalty; base scenario ≈ −0.2 pp/q at a +13 % gap
      const pull = -sc.reversion * 10 * valuationGap
      const g = W_MOMENTUM * momentum + W_FUND * fundamental + W_VAL * pull // % q/q
      price = price * (1 + g / 100)
      valuationGap = valuationGap * (1 - sc.reversion * 4) + (g - 1.2) * 0.15 // gap grows if growth ≫ income trend

      const sigmaH = sigmaYoY * Math.sqrt(h / 4) * sc.uncertainty * 0.55
      points.push({
        quarter: addQuarters(LAST_MEASURED_QUARTER, h),
        value: Math.round(price),
        lo: Math.round(price * (1 - (sigmaH * 1.28) / 100)), // ~80 % interval
        hi: Math.round(price * (1 + (sigmaH * 1.28) / 100)),
      })
    }

    return {
      id: sc.id,
      label: sc.label,
      probability: sc.probability,
      assumptions: sc.assumptions,
      points,
    }
  })
}

export const FORECASTS = buildForecasts()

export function horizonSummary(): {
  horizon: string
  quarters: number
  scenarios: { id: string; label: string; price: number; pct: number; lo: number; hi: number }[]
}[] {
  const last = NATIONAL_PRICE.values[NATIONAL_PRICE.values.length - 1]!
  return [
    { horizon: '12 mesiacov', quarters: 4 },
    { horizon: '3 roky', quarters: 12 },
    { horizon: '5 rokov', quarters: 20 },
  ].map(({ horizon, quarters }) => ({
    horizon,
    quarters,
    scenarios: FORECASTS.map((f) => {
      const p = f.points[quarters - 1]
      return {
        id: f.id,
        label: f.label,
        price: p.value,
        pct: ((p.value - last) / last) * 100,
        lo: p.lo,
        hi: p.hi,
      }
    }),
  }))
}

export const HORIZONS = horizonSummary()
